# Generated by Django 3.1 on 2021-07-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('reg_no', models.IntegerField(default=0)),
                ('pwd', models.CharField(max_length=13)),
            ],
        ),
    ]
