# Generated by Django 3.1 on 2021-07-06 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='User_Model',
        ),
    ]
