# Generated by Django 3.1 on 2021-07-06 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_auto_20210706_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_type', models.CharField(max_length=30)),
            ],
        ),
    ]
