# Generated by Django 3.1 on 2021-07-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_quiz_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_model',
            name='quiz_type',
            field=models.IntegerField(default=0),
        ),
    ]
